name: "dt"
version: "0.5.1-machecazzo"
usage: "Distribution Tooling for Helm"
description: "Distribution Tooling for Helm"
command: "$HELM_PLUGIN_DIR/bin/dt"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh -u"
